jobs:
  - deployment: deploy
    environment: CE-QA
    strategy:
      runOnce:
        deploy:
          steps:
            - template: 'replace-tokens.yml'
            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'CoreInteract DEVELOPMENT (abde34c8-4147-4bf7-9744-54056591ff01)'
                appType: 'webAppLinux'
                appName: 'app-coreview360-client'
                deployToSlotOrASE: true
                resourceGroupName: 'appservices'
                slotName: 'qa'
                package: '$(Pipeline.Workspace)/coreengage'
                startUpCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'
